#!/usr/bin/env bash
set -euo pipefail

file="${1:?file argument required}"
dir="$(dirname "$file")"

root="$(git -C "$dir" rev-parse --show-toplevel)"
remote="$(git -C "$root" remote get-url origin)"
branch="$(git -C "$root" rev-parse --abbrev-ref HEAD)"

case "$remote" in
    git@github.com:*)
        repo="${remote#git@github.com:}"
        repo="${repo%.git}"
        ;;
    https://github.com/*)
        repo="${remote#https://github.com/}"
        repo="${repo%.git}"
        ;;
    *)
        echo "not a github remote: $remote" >&2
        exit 1
        ;;
esac

relative="${file#$root/}"

if [ -d "$file" ]; then
    ref_type="tree"
else
    ref_type="blob"
fi

printf '%s' "https://github.com/$repo/$ref_type/$branch/$relative"
