# Interactive shells. PATH is built in .zsh_path.zsh (via .zshenv / .zprofile).

# ── Prompt ──────────────────────────────────────────────────────────────────
# Powerlevel10k instant prompt. Must stay at the top of this file.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# zsh plugins are plain git clones made by mise ([bootstrap.repos] in the dotfiles
# repo's mise.toml). Refresh with `mise bootstrap repos update`.
ZSH_PLUGINS="$HOME/.local/share/zsh/plugins"

source "$ZSH_PLUGINS/powerlevel10k/powerlevel10k.zsh-theme"
[[ -f "${ZDOTDIR:-$HOME}/.p10k.zsh" ]] && source "${ZDOTDIR:-$HOME}/.p10k.zsh"

# ── Environment ─────────────────────────────────────────────────────────────
export EDITOR=hx
export MANPAGER="sh -c 'col -bx | bat -l man -p'"   # colored man pages via bat
export OPENCODE_ENABLE_EXA=1                          # OpenCode: enable the web-search tool (Exa)

# "Open in editor" from dev servers (Storybook, Vite) goes through the launch-editor
# package, which prefers a running GUI editor over $EDITOR. Only these two variables
# jump that queue; the handler opens the file in Helix in a new Herdr tab.
export LAUNCH_EDITOR="$HOME/scripts/helix/hx-open"
export REACT_EDITOR="$LAUNCH_EDITOR"

# ── Aliases ─────────────────────────────────────────────────────────────────
# Interactive shells only. These swap defaults for nicer tools (ls -> eza, cat -> bat).
# Non-interactive shells that source this file (agent shells do) keep the plain tools.
if [[ -o interactive ]]; then
  alias rc='source $HOME/.zshrc'
  alias zshrc='hx $HOME/.zshrc'
  alias h='hx'
  alias g='git'
  alias ls='eza --color --icons --all --group-directories-first'
  alias ll='eza --long --header --time-style=relative --no-filesize --tree --level=2 --color --icons --all --group-directories-first'
  alias cat='bat'
  alias caff='caffeinate -di'   # hold off display + idle sleep until Ctrl-C
  alias ...='popd'
  alias -g -- --help='--help 2>&1 | bat --language=help --style=plain'

  # List the directory after every cd. Defined after the aliases so `ls` here
  # expands to the eza alias above.
  autoload -Uz add-zsh-hook
  _auto_ls() { ls; }
  add-zsh-hook chpwd _auto_ls
fi

# ── Keybindings ─────────────────────────────────────────────────────────────
# Up/Down search history using what is already typed.
bindkey "^[[A" history-search-backward
bindkey "^[[B" history-search-forward

# ── Shell options ───────────────────────────────────────────────────────────
setopt autocd            # cd by typing a directory name
setopt auto_pushd        # cd pushes onto the directory stack
setopt pushd_ignore_dups
setopt pushd_silent

HISTSIZE=9999
HISTFILE="$HOME/.zsh_history"
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_find_no_dups

# ── Completions ─────────────────────────────────────────────────────────────
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'      # case-insensitive
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*:git-checkout:*' sort false
zstyle ':completion:*' menu no                              # let fzf-tab take over
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 -a --color=always $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'eza -1 -a --color=always $realpath'

# ~/.zfunc holds completions generated by `mise run bootstrap` (mise, herdr, gh).
fpath=("$HOME/.zfunc" "$ZSH_PLUGINS/zsh-completions/src" $fpath)
autoload -Uz compinit
compinit

source "$ZSH_PLUGINS/fzf-tab/fzf-tab.plugin.zsh"   # after compinit, before autosuggestions

# ── Tools ───────────────────────────────────────────────────────────────────
eval "$(mise activate zsh)"   # tool PATH + env, recomputed at each prompt
eval "$(fzf --zsh)"           # Ctrl-R history, Ctrl-T files, Alt-C dirs

# Machine-local interactive config. Untracked on purpose.
[[ -f "$HOME/.localrc" ]] && source "$HOME/.localrc"

source "$ZSH_PLUGINS/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
source "$ZSH_PLUGINS/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh"   # last plugin

# zoxide replaces cd. Last, because it overrides the cd command. Interactive only:
# non-interactive shells that source this file keep the builtin cd and do not feed
# the zoxide database.
if [[ -o interactive ]]; then
  eval "$(zoxide init --cmd cd zsh)"
fi
