
# tap repositories and their packages

tap homebrew/core
brew agent-browser
brew antidote
brew bat
brew direnv
brew eza
brew fnm
brew fzf
brew gh
brew helix
brew ripgrep
brew stow
brew zoxide

tap homebrew/cask
cask font-caskaydia-cove-nerd-font
cask font-meslo-for-powerlevel10k
cask ghostty

tap rcmdnk/file
brew brew-file
