
# tap repositories and their packages

tap homebrew/core
brew antidote
brew bat
brew direnv
brew eza
brew fnm
brew fzf
brew gleam
brew stow
brew zoxide

tap homebrew/cask
cask arc
cask font-caskaydia-cove-nerd-font
cask font-meslo-for-powerlevel10k
cask raycast
cask zed

tap homebrew/bundle

tap homebrew/cask-fonts

tap pikachuexe/freetube
cask pikachuexe-freetube

tap rcmdnk/file
brew brew-file
