
# tap repositories and their packages

tap homebrew/core
brew antidote
brew bat
brew biome
brew direnv
brew defuddle
brew eza
brew fnm
brew fzf
brew gh
brew git-lfs
brew glow
brew helix
brew navi
brew pyright
brew ripgrep
brew stow
brew terminal-notifier
brew typescript-language-server
brew worktrunk
brew zellij
brew zoxide

tap homebrew/cask
cask font-jetbrains-mono-nerd-font
cask ghostty
cask obsidian


tap rcmdnk/file
brew brew-file

tap anomalyco/tap
brew opencode
